from dataclasses import dataclass
from typing import Self


class Point:
    def __init__(self, x: float, y: float) -> None:
        self.x = x
        self.y = y

    def __add__(self, other) -> Self:
        return Point(self.x + other.x, self.y + other.y)


class Speed:
    ...


class Acceleration:
    ...


@dataclass
class Sun:
    mass: 1.0
    radius: 1.0
    position: Point(0.0, 0.0)
    speed: 0.0
    colour: 'yellow'
    screen_radius: 1.0
    forces: None

@dataclass
class Mercury:
    mass: 1.66 * 10**-7
    radius: ...
    position: ...
    speed: 0.0
    colour: ...
    screen_radius: ...
    forces: ...

@dataclass
class Venus:
    mass: 2.45 * 10**-6
    radius: ...
    position: ...
    speed: 0.0
    colour: 'brown'
    screen_radius: ...
    forces: ...

@dataclass
class Earth:
    mass: 3.00 * 10**-6
    radius: ...
    position: ...
    speed: 0.0
    colour: 'green'
    screen_radius: ...
    forces: ...

@dataclass
class Mars:
    mass: 3.23 * 10**-7
    radius: ...
    position: ...
    speed: 0.0
    colour: 'orange'
    screen_radius: ...
    forces: ...

@dataclass
class Jupiter:
    mass: 9.54 * 10**-4
    radius: ...
    position: ...
    speed: 0.0
    colour: 'gray'
    screen_radius: ...
    forces: ...

@dataclass
class Io:
    mass: 4.7 * 10**-8
    radius: ...
    position: ...
    speed: 0.0
    colour: ...
    screen_radius: ...
    forces: ...

@dataclass
class Europe:
    mass: 2.5 * 10**-8
    radius: ...
    position: ...
    speed: 0.0
    colour: ...
    screen_radius: ...
    forces: ...

@dataclass
class Ganymede:
    mass: 7.8 * 10**-8
    radius: ...
    position: ...
    speed: 0.0
    colour: ...
    screen_radius: ...
    forces: ...

@dataclass
class Callisto:
    mass: 5.7 * 10**-8
    radius: ...
    position: ...
    speed: 0.0
    colour: ...
    screen_radius: ...
    forces: ...

@dataclass
class Saturn:
    mass: 2.86 * 10**-4
    radius: ...
    position: ...
    speed: 0.0
    colour: ...
    screen_radius: ...
    forces: ...

@dataclass
class Uranus:
    mass: 4.37 * 10**-5
    radius: ...
    position: ...
    speed: 0.0
    colour: ...
    screen_radius: ...
    forces: ...

@dataclass
class Neptune:
    mass: 5.15 * 10**-5
    radius: ...
    position: ...
    speed: 0.0
    colour: 'blue'
    screen_radius: ...
    forces: ...

